sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t locnguyen1986/docker-react -f Dockerfile.dev .

script:
    - docker run locnguyen1986/docker-react npm run test -- --coverage